# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Deploy your apps to your own Platform as a Service."
  homepage "https://deckrun.com/"
  version "0.0.65"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.0.65/deck_Darwin_x86_64.tar.gz"
      sha256 "847feec06a6fa68dc9a702a5f40792e4a6458a0bdff2d7b2a53974bcd329a882"

      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.0.65/deck_Darwin_arm64.tar.gz"
      sha256 "d1db4a32aa3f63257fd096255dfe960acb96a0d9a3ad8f5373d508c50744b870"

      def install
        bin.install "deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deckrun/deck-cli/releases/download/v0.0.65/deck_Linux_x86_64.tar.gz"
        sha256 "374ee1d81b0c4428c3e1401266a60704450c578e4bb65e564ec60b1695420793"

        def install
          bin.install "deck"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deckrun/deck-cli/releases/download/v0.0.65/deck_Linux_arm64.tar.gz"
        sha256 "9aff0264cc114d5c8abb62287c73ca5ab1eb8242a4d0cb3f5e52cdb77f38dde4"

        def install
          bin.install "deck"
        end
      end
    end
  end

  test do
    system "#{bin}/deck version"
  end
end
