# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Deploy your apps to your own Platform as a Service."
  homepage "https://deckrun.com/"
  version "0.1.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.27/deck_Darwin_x86_64.tar.gz"
      sha256 "849d602461086f371585ae7198d29e1c1c824278f4c8753b7ec07fe9f32390ab"

      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.27/deck_Darwin_arm64.tar.gz"
      sha256 "f04f4bf5c667e561c37f51243644a5fc0506e4956473c178d0b253d846130b78"

      def install
        bin.install "deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.27/deck_Linux_x86_64.tar.gz"
      sha256 "f285f96dcea18e17b15c4815a56923e35dca7d82d3c6f403a6d3bbee64307d81"
      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.27/deck_Linux_arm64.tar.gz"
      sha256 "29f662e091b86926459338dfaeb1e72f6aa2ce4aa2c1a52bf806d929918ea9b6"
      def install
        bin.install "deck"
      end
    end
  end

  test do
    system "#{bin}/deck version"
  end
end
