# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deck < Formula
  desc "Deploy your apps to your own Platform as a Service."
  homepage "https://deckrun.com/"
  version "0.1.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.19/deck_Darwin_x86_64.tar.gz"
      sha256 "c22c931f9915a90d48e4dcf0dceaa1dc72464562a479a32256b7291f92983705"

      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.19/deck_Darwin_arm64.tar.gz"
      sha256 "e0c6e58dfa945f5ef140a7e8392023987f21d30fd8af66c2a4041a11c0b4bc3b"

      def install
        bin.install "deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.19/deck_Linux_x86_64.tar.gz"
      sha256 "c4362ab8d9cf95af4d212cfd595016707a7acc8d7ccc09963f3d1aa4b685c1e3"
      def install
        bin.install "deck"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/deckrun/deck-cli/releases/download/v0.1.19/deck_Linux_arm64.tar.gz"
      sha256 "ed7f2b8a4f2abbde8359607c4d8c28bf795ce96c5d9c3eceeb7cf7b9903357ea"
      def install
        bin.install "deck"
      end
    end
  end

  test do
    system "#{bin}/deck version"
  end
end
